import { createClient } from '@supabase/supabase-js'
import { notFound } from 'next/navigation'
import Link from 'next/link'
import fs from 'fs'
import path from 'path'
import ShareModal from './components/ShareModal'
import DownloadButton from './components/DownloadButton'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
)

interface PageProps {
  params: Promise<{ id: string }>
  searchParams?: Promise<{ [key: string]: string | string[] | undefined }>
}

// Function to clean content from potential formatting artifacts
function cleanContent(content: string): string {
  if (!content) return content;
  
  return content
    // Remove HTML code block markers
    .replace(/^```html\s*/i, '')
    .replace(/\s*```$/i, '')
    // Remove generic code block markers
    .replace(/^```\s*/, '')
    .replace(/\s*```$/, '')
    // Remove leading/trailing newlines and whitespace
    .replace(/^\s*\n+/, '')
    .replace(/\n+\s*$/, '')
    .trim();
}

export default async function Page({ params, searchParams }: PageProps) {
  const { id } = await params
  const resolvedSearchParams = searchParams ? await searchParams : {}

  try {
    const { data: infographic, error } = await supabase
      .from('infographics')
      .select('content, user_query, created_at, generation_status, template_id')
      .eq('id', id)
      .single()

    if (error || !infographic) {
      notFound()
    }

    if (infographic.generation_status !== 'READY') {
      return (
        <div className="min-h-screen bg-gradient-to-b from-slate-900 to-black flex items-center justify-center">
          <div className="text-center text-white">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-400 mx-auto mb-4" />
            <p className="text-lg">Generating Star Graph...</p>
            <p className="text-sm text-gray-400 mt-2">Status: {infographic.generation_status}</p>
          </div>
        </div>
      )
    }

    // Clean the content before rendering
    const cleanedContent = cleanContent(infographic.content);
    const shareUrl = `${process.env.NEXT_PUBLIC_SITE_URL || 'https://stargraphs.vercel.app'}/${id}`;
    const shareTitle = `Check out this Star Graph: ${infographic.user_query}`;

    return (
      <main className="min-h-screen bg-gradient-to-b from-slate-900 to-black">
        {/* Load template-specific CSS if template_id exists */}
        {infographic.template_id && (
          <link rel="stylesheet" href={`/styles/${infographic.template_id}.css`} />
        )}
        
        {/* Add icon library CSS */}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.13.1/font/bootstrap-icons.min.css" />
        
        <div 
          className="w-full h-full"
          dangerouslySetInnerHTML={{ __html: cleanedContent }}
        />
        
        {/* Footer with action buttons and branding */}
        <footer className="relative border-t border-slate-700 py-8 w-full font-sans text-base">
          <div className="absolute inset-0 bg-slate-800/80 backdrop-blur-sm" aria-hidden="true"></div>
          <div className="relative w-full m-auto px-6 text-center">
            {/* Data sources */}
            <div className="mb-4">
              <p className="text-gray-500 text-xs font-sans">
                Data sourced from{' '}
                <a 
                  href="https://www.themoviedb.org/" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="text-gray-400 hover:text-blue-400 transition-colors"
                >
                  TMDB
                </a>
                {' '}and{' '}
                <a 
                  href="https://www.wikipedia.org/" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="text-gray-400 hover:text-blue-400 transition-colors"
                >
                  Wikipedia
                </a>
              </p>
            </div>
            
            {/* Action buttons */}
            <div className="flex justify-center gap-6 mb-6">
              <ShareModal 
                url={shareUrl}
                title={shareTitle}
                description={`Interactive Star Graph about ${infographic.user_query}`}
              />
              
              <DownloadButton infographicId={id} />
            </div>
            
            {/* Branding */}
            <div>
              <p className="text-gray-400 text-sm font-sans !font-normal">
                Generated by{' '}
                <Link 
                  href="/" 
                  className="text-white font-semibold hover:text-blue-400 transition-colors font-sans"
                >
                  Star Graphs
                </Link>
              </p>
            </div>
          </div>
        </footer>

        {/* Metadata for SEO */}
        <div className="sr-only">
          <h1>Star Graph: {infographic.user_query}</h1>
          <p>Generated: {new Date(infographic.created_at).toLocaleDateString('en-US')}</p>
        </div>
      </main>
    )
  } catch (error) {
    console.error('Error loading Star Graph:', error)
    notFound()
  }
}

export async function generateMetadata({ params }: PageProps) {
  const { id } = await params

  try {
    const { data: infographic } = await supabase
      .from('infographics')
      .select('user_query, created_at, template_id')
      .eq('id', id)
      .single()

    if (!infographic) {
      return {
        title: 'Star Graph not found - Star Graphs'
      }
    }

    return {
      title: `${infographic.user_query} - Star Graphs`,
      description: `Interactive Star Graph about ${infographic.user_query}. Generated on ${new Date(infographic.created_at).toLocaleDateString('en-US')}.`,
      openGraph: {
        title: `${infographic.user_query} - Star Graphs`,
        description: `Stylish Star Graph about ${infographic.user_query}`,
        type: 'website'
      }
    }
  } catch (error) {
    return {
      title: 'Star Graphs - Movie Star Graphs'
    }
  }
}

export async function generateStaticParams() {
  try {
    const { data: infographics } = await supabase
      .from('infographics')
      .select('id')
      .eq('generation_status', 'READY')

    if (!infographics) {
      return []
    }

    return infographics.map((infographic) => ({
      id: infographic.id
    }))
  } catch (error) {
    console.error('Error generating static params:', error)
    return []
  }
}